# Generated by Django 4.2.4 on 2023-08-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_creater_alter_post_liked_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='me',
        ),
    ]
